"""change rent_value from float to decimal

Revision ID: 1dd5c43376da
Revises: 9319f69a03c7
Create Date: 2025-10-31 11:51:55.677977

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1dd5c43376da"
down_revision: Union[str, Sequence[str], None] = "9319f69a03c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "property",
        "rent_value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=10, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "property",
        "rent_value",
        existing_type=sa.DECIMAL(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
