"""configuration key unique

Revision ID: 3a4847653d4e
Revises: 1dd5c43376da
Create Date: 2025-10-31 18:17:06.041914

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3a4847653d4e"
down_revision: Union[str, Sequence[str], None] = "1dd5c43376da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "configuration", ["key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "configuration", type_="unique")
    # ### end Alembic commands ###
